name: Deploy nodejs code on ExCloud

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: checkout Code
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v4
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}  
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4
         
            - name: Docker Build and Push
              run: | 
                docker build -t divyansh576dev/devops-first .
                docker push divyansh576dev/devops-first

            - name: Deploy on ExCloud
              uses: appleBoy/ssh-action@v1.0.3
              with:
                host: 210.79.129.233
                username: ubuntu
                key: ${{ secrets.PRIVATE_KEY}}
                script: |
                  # CD into /home/ubuntu/DevOps-
                    cd /home/ubuntu/DevOps-

                  # git pull
                   git pull origin main

                  # make sure to pull a fresh copy of push divyansh576dev/devops-first
                   sudo docker-compose pull

                  # docker compose u- -d
                   sudo docker-compose up -d

                  # Clean up old/unused images
                   sudo docker image prune -f